server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cartdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
